#include <stdio.h>
int main (void)
{
	/*Initialize variables*/
	int lakeid, beachnumber, numofsamples, x;
	double orgsin100ml, avg, total;
	/*Read in file and print headers*/
	FILE *in;
	in = fopen ("aug15.data", "r");
	printf("\nLake\t\tBeach\t\tAverage EColi Level\tRecommendation");
	printf("\n----\t\t-----\t\t--------------------\t---------------\n");

	fscanf(in, "%d%d%d", &lakeid, &beachnumber, &numofsamples);
	
	/*Begin while loop until file ends*/
	while (!(feof(in)))
	{
	
	/*Check lake ID*/
	if (lakeid == 1)
	{
		
		
			if (beachnumber == 100)
		printf("Ontario         Kew Beach");
			else if (beachnumber == 101)
		printf("Ontario         Sunnyside Beach");
			else if (beachnumber == 103)
		printf("Ontario         Sandbanks");
	}	 
		
		
	else if (lakeid == 2)
	
	{
		
			if (beachnumber == 201)
		printf ("Erie            Port Dover");
			else if (beachnumber == 202)
		printf("Erie            Port Burwell");
			else if (beachnumber == 203)
		printf("Erie             Crystal Beach");
	}	 
		

	
	else if (lakeid == 3)

	{

	
			if (beachnumber == 301)
		printf("Huron           Goderich");
			else if (beachnumber == 302)
		printf("Huron           Sauble Beach");
			else if (beachnumber == 303)
		printf("Huron           Kincardine");
	}	
		
	
	
	
	
			else if (lakeid == 4)
		printf("Muskoka         Muskoka Beach");
			else if (lakeid == 5)
		printf("Simcoe          Sibbald Point");
	
		/*Compute total (sum) and average*/
		total = 0;
		for (x = 1; x <= numofsamples; x++)
		{
			fscanf(in, "%lf", &orgsin100ml);
			total = total + orgsin100ml;
		}
	
		
		avg = (double)total / (double)numofsamples;
		
		/*Conditions for number of samples and different average values*/
		if (numofsamples >= 3)
		{
			if (avg > 50)
			{
			printf("\t%10.2lf", avg);
			printf("\t\tCLOSED\n");
				
			}
			else if (avg < 50)
			{
				printf("\t%10.2lf", avg);
				printf("\t\tOPEN\n");
			}
		}
		else 
		{
			avg = 0;
			printf("   \t%10.2lf", avg);
			printf("\t\tINSUFFICIENT DATA\n");
		}
		/*Scan in next line,*/
		fscanf(in, "%d%d%d", &lakeid, &beachnumber, &numofsamples);
	}
	/*Close file*/
	fclose(in);
	printf("\nReport from july15.data generated by Amit Rambaran");
	return(0);
}

